#!/usr/bin/lua

Profiles = {}

function RunCommand(command)
   local cmd = io.popen(command)
   local cout = cmd:read("*a")
   local exitcode = cmd:close()
   local out = {cout, exitcode}
   return out
end

function Checkroot()
   local out = RunCommand("whoami")
   local username = out[1]:gsub("%s+", "") -- Remove leading/trailing whitespace
   if username == "root" then
       print("I am at your service, my king")
   else
       print("Do you mind giving root permissions?")
       os.exit(1)
   end
end

function clear_file(cfile)
    RunCommand("dd if=/dev/null of="..cfile)
end

function ask_yn(question)
   local out = RunCommand("gum confirm \""..question.."\"")
   local exitcode = out[2]
   if exitcode == 0 then
       return true
   else
       return false
   end
end

function ask(args)
   local out = RunCommand("gum choose "..args)
   local cout = out[1]
   return cout
end

function getdeps()
   print("Checking dependencies...")
	for _, pkg in ipairs({"gum", "cpupower"}) do
		if not RunCommand(">/dev/null pacman -Qq " .. pkg) then
			error("dependency " .. pkg .. " not present", 0)
		end
	end
end

function create_profile(name, packages, postshellcommand)
   local ProfileData = {Pkgs = packages, PostShell = postshellcommand}
   Profiles[name] = ProfileData
   return 0
end

function install_pkgs(packages)
    local out = RunCommand("pacman --noconfirm -S "..packages .." " .."> /dev/null 2>&1")
end


function get_profiles(inputTable)
    local table_names = ""
    for key, _ in pairs(inputTable) do
      table_names = table_names .. key .. " "
    end
    return table_names
end

function write_file(file, data)
    local ifile = io.open(file, "a")
    ifile:write(data)
    ifile:close()
end

function initfiles()
    local out = RunCommand("cat /etc/virbos-profile-old")
    local exitcode = out[2]
    if exitcode == 0 then
        dofile("/etc/virbos-profile-old")
        old_profile_exists = true
    else
        RunCommand("touch /etc/virbos-profile-old")
        old_profile_exists = false
    end
end

function clear_pkgs(packages)
    RunCommand("pacman --noconfirm -R "..packages)
    local out = RunCommand("pacman -Qdtq")
    local orphanaged_packages = out[1]
    RunCommand("pacman --noconfirm -Rns "..orphanaged_packages)

end

function save_profileData(profilename, profilepkgs)
    clear_file("/etc/virbos-profile-old")
    write_file("/etc/virbos-profile-old", "oldprofilename = \""..profilename.."\"")
    write_file("/etc/virbos-profile-old", "\noldpkgs = \""..profilepkgs.."\"")
end

  function select_profile()
    dofile("/etc/virbos-profile-old")
    local profs = get_profiles(Profiles)
    RunCommand("clear")
    local out = ask(profs)
    local out = out:gsub('\n$', "", 1)
    local profile = Profiles[out]
    oldprofilename = oldprofilename:gsub('\n$', "", 1)
    if old_profile_exists == true then
        if out == oldprofilename then
            print("The selected profile is already selected, exiting...")
            os.exit()
        else
            print("Changing profile...")
            clear_pkgs(oldpkgs)
        end
    else
        print("Saving profile...")
        save_profileData(out, profile.Pkgs)
    end

    print("Downloading profile packages...")
    install_pkgs(Profiles[out].Pkgs)
    print("Running post shell commands...")
    RunCommand(Profiles[out].PostShell)


end
-- the following commands were used in testing of the script. Please remove them when using the profile chooser in real-world.
Checkroot()
getdeps()
initfiles()
create_profile("testProfile", "cheese", "cheese > /dev/null")
select_profile()
print(oldprofilename)
